language: cpp

sudo: required

matrix:
  include:
    - os: linux
      compiler: gcc
      env: Tr_Compiler_Version="default"
    - os: linux
      compiler: gcc
      env: Tr_Compiler_Version="5"
    - os: linux
      compiler: gcc
      env: Tr_Compiler_Version="6"
    - os: linux
      compiler: gcc
      env: Tr_Compiler_Version="7"
    - os: linux
      compiler: gcc
      env: Tr_Compiler_Version="8"
    - os: linux
# clang
      compiler: clang
      env: Tr_Compiler_Version="default"
    - os: linux
      compiler: clang
      env: Tr_Compiler_Version="6.0"
# osx
    - os: osx
      osx_image: xcode9.2
    - os: osx
      osx_image: xcode9.3beta

  allow_failures:
  - os: osx

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./.travis-before_install.sh "$CC" "$Tr_Compiler_Version"; fi

script:
  - ./configure --prefix=$PWD/temp-build
  - make
  - make install
  - cd test
  - ./basic.sh
  - rm -rf tmp-home
  - ./purging.sh
  - cd ..
  - make uninstall

notifications:
  slack: removetowaste:u16fiNsaMeLmg7J4WXifW3Zm
